# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "oc-spawn-monitor"
primary_region = "sjc"

[build]

[env]
  CHECK_INTERVAL = "60"
  FILTER_MIN_DIFFICULTY = "simple"
  FILTER_MIN_SCOPE = "1"

[processes]
  app = "node oc-monitor-daemon.js"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
